### ISSUE TITLE
Strange styling / css issues when navigating around the site.

### ISSUE THREAD

**Issue by boyney123** [boyney123/react.explore-tech.org#10]
On first load the site looks like this:

![image](https://user-images.githubusercontent.com/3268013/52657043-a4e45680-2eef-11e9-9068-1b2aa7fd7d6f.png)

When you go to the next page:

![image](https://user-images.githubusercontent.com/3268013/52657055-add52800-2eef-11e9-8cc2-bf86c8c12c18.png)

When you go back:

![image](https://user-images.githubusercontent.com/3268013/52657070-b62d6300-2eef-11e9-92ae-3141e01f163b.png)

Its like the styles are not loading? If I refresh the styles come in fine?

**Comment by jamesg1** [comment]
Nice project happy to help out and fix this one.

**Comment by boyney123** [comment]
Hey @jamesg1 thanks!

Looks like I might have already fixed it yesterday, I was including Bulma in the `Header` component, but now I use the `npm` package. Seems to have fixed the issue! 

Thanks for offering though @jamesg1 maybe you can help out with some others :)? 👍
