### ISSUE TITLE
Adding nivo.rocks into charts category

### ISSUE THREAD

**Issue by devdanco** [boyney123/react.explore-tech.org#12]
It would be really nice to have [nivo.rocks](https://github.com/plouc/nivo) in charts category. It is amazing library.
Nivo provides React components to build dataviz apps, it's built on top of d3.

**Comment by boyney123** [comment]
Thanks @devdanco , il add it now 👍 

For future reference you should be able to create a pull request to add things, I have written scripts to easily add material.

For example, if you run `npm run add:chart https://github.com/plouc/nivo` it would automaticlly add the website and also commmit for you :), then you just submit the PR.

**Comment by devdanco** [comment]
Awesome ;) Next time I will definitely submit PR ;)

**Comment by boyney123** [comment]
Cool thanks @devdanco , I have added it to the project, its just building now

**Comment by boyney123** [comment]
Added 👍 https://react.explore-tech.org/Charts/nivo/nivo/
