### ISSUE TITLE
add an Example project

### ISSUE THREAD

**Issue by Pau1fitz** [boyney123/react.explore-tech.org#13]
Is it possible to add an example project?

I couldn't see how to do this in the PR guidance.

I would like to add [this React Spotify clone](https://github.com/Pau1fitz/react-spotify).

**Comment by boyney123** [comment]
Yeah sorry I need to make it more clear.

You can find out how here: https://github.com/boyney123/react.explore-tech.org/blob/master/README.md#contributing

Let me know if you need help.

**Comment by Pau1fitz** [comment]
This was clear, but it isn't a component, it's an example. Or should it be added as a component.

I tried `npm run add:Examples https://github.com/Pau1fitz/react-spotify`

**Comment by Pau1fitz** [comment]
ahhh, I have just seen the updated guidelines [here](https://github.com/boyney123/react.explore-tech.org/blob/master/CONTRIBUTING.md#adding-a-material-to-the-website). 👍🏼
