### ISSUE TITLE
Add Emotion to styles

### ISSUE THREAD

**Issue by GA-MO** [boyney123/react.explore-tech.org#17]
https://emotion.sh/docs/introduction

**Comment by boyney123** [comment]
Great idea @GA-MO , did you fancy trying to raise a PR? 

I have documented how you would do this here: https://github.com/boyney123/react.explore-tech.org/blob/master/CONTRIBUTING.md

**Comment by boyney123** [comment]
Emotion has been added to the website 👍 thanks!
